apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: sleepr
  region: ap-southeast-1

nodeGroups:
  - name: ng-1
    instanceType: t2.micro
    desiredCapacity: 3
    # volumeSize: 80
    # ssh:
    #   allow: true # will use ~/.ssh/id_rsa.pub as the default ssh key