apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: payments
  name: payments
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments
  template:
    metadata:
      labels:
        app: payments
    spec:
      containers:
      - image: asia-east1-docker.pkg.dev/eminent-carver-435308-s2/payments/production
        name: payments
        env:
          - name: PORT_PAYMENT
            value: '3003'
          - name: NOTIFICATION_HOST
            value: '0.0.0.0'
          - name: NOTIFICATION_PORT
            value: '3004'
          - name: STRIPE_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: stripe
                key: apiKey
        ports:
          - containerPort: 3003
