apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: reservations
  name: reservations
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reservations
  template:
    metadata:
      labels:
        app: reservations
    spec:
      containers:
      - image: asia-east1-docker.pkg.dev/eminent-carver-435308-s2/reservations/production
        name: reservations
        env:
          - name: MONGODB_URI
            valueFrom:
              secretKeyRef:
                name: mongodb
                key: connectionString
          - name: PORT
            value: '3000'
          - name: AUTH_HOST
            value: 'auth'
          - name: AUTH_PORT
            value: '3002'
          - name: PAYMENTS_HOST
            value: 'payments'
          - name: PAYMENTS_PORT
            value: '3003'
        ports:
          - containerPort: 3000
